# mgconfig configuration definitions 
# for advanced example configuration

- section: secure_store
  prefix: sec
  configs:

  - name: securestore_file
    type: path
    readonly: True
    default: '$(app_configdir)/$(app_name)_sec.json'
    env: SECURESTORE_FILE
    description: filepath of secure store file

  - name: master_key_keystore
    type: str
    readonly: True
    default: env
    description:


  - name: master_key_item_name
    type: str
    readonly: True
    default: APP_KEY
    description: item name for master key for protection of secure storage (read only) (never displayed)

  - name: keyring_service_name
    type: str
    readonly: True
    env: KEYRING_SERVICE
    default: mgconfig_test
    description:


  - name: keyfile_filepath
    type: path
    readonly: True
    env: KEYFILE_PATH
    default: $(app_basedir)/configs
    description:


- section: Test Secrets Section
  prefix: tst_secrets
  configs:

  - name: password
    type: secret
    description: test item for a password which should be stored encrypted in secure store file
